### ISSUE TITLE
Use SupervisorJob by default?

### ISSUE THREAD

**Issue by AllanWang** [jguerinet/Suitcase#5]
Your default job from `MainScope` is a normal job. You may want to use [SupervisorJob](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-supervisor-job.html) instead.

In normal jobs, a child failing will cancel the parent, so any other requests will also be cancelled. Supervisor job allows children to fail independently, so if you have two components loading, or a refresh option that sometimes fails, one call will not affect the other.

**Comment by jguerinet** [comment]
The latest version of coroutines comes with its on `MainScope` built in, which I will switch to. It's currently marked as experimental, with stable support scheduled for the next minor version. Depending on when that comes, I'll either wait until that's available or switch this to a `SupervisorJob` until it's stable.
